version: '3.9'

services:
  frontend:
    build:
      context: frontend
    ports:
      - '3000:80'
    volumes:
      - ./frontend:/app:delegated
    environment:
      - NODE_ENV=production

volumes:
  postgres-data:
  root-home:
