# We specify volumes in override.yml, because volumes don't work well in a
# docker-in-docker setup (the paths of parent host rarely match the nested containers)
version: '3.7'

services:
  postgres:
    ports:
      - '15432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    volumes:
      - ./backend:/app:delegated
      - root-home:/root:delegated
    depends_on:
      postgres:
        condition: service_healthy
