"""default model

Revision ID: 4c02ff737b1d
Revises: e3096b6780d9
Create Date: 2022-10-15 10:58:10.036659

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '4c02ff737b1d'
down_revision = 'e3096b6780d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
