name: backend-test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend
        id: docker_build_backend
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: 'e-commerce-website-backend:latest'
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: backend
          load: true

      - name: Start containers and run tests
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          cat .env
          docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.ci.yml up -d
          docker-compose exec -T postgres createdb -U postgres apptest
          docker-compose exec -T backend alembic upgrade head
          docker-compose exec -T backend pytest -v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log docker status
        if: ${{ always() }}
        run: |
          docker-compose ps
          docker-compose logs -t
